config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'

  get 'search_stock', to: 'stocks#search'
  post 'refresh_stock_prices', to: 'stocks#refresh_prices'

  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials[:iex_client][:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    begin
      new(
        ticker: ticker_symbol,
        name: client.company(ticker_symbol).company_name,
        last_price: client.price(ticker_symbol)
      )
    rescue IEX::Errors::SymbolNotFoundError => _exception
      nil
    end
  end

  def self.refresh_prices
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials[:iex_client][:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    all.each do |stock|
      stock.last_price = client.price(stock.ticker)
      stock.save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  MAX_STOCK_COUNT = 10

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :matches, lambda { |x|
    where('email ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ?',
          "%#{x}%", "%#{x}%", "%#{x}%")
  }

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    'anonymous'
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.find_by(ticker: ticker_symbol)
    return false if stock.nil?

    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < MAX_STOCK_COUNT
  end

  def not_friends_with?(friend)
    !friends.where(id: friend.id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    current_user.friendships.build(friend_id: params[:friend])
    if current_user.save
      flash[:notice] =
        "You are now friends with #{current_user.friendships.last.friend.full_name}!"
      redirect_to my_friends_path
    else
      flash[:alert] = 'Something went wrong...'
      redirect_to root_path
    end
  end

  def destroy
    friendship = Friendship.find_by(user_id: current_user, friend_id: params[:id])
    friendship.destroy

    flash[:notice] = "You are no longer following #{friendship.friend.full_name}"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock].upcase)
      if @stock.present?
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result' }
      end
    end
  end

  def refresh_prices
    respond_to do |format|
      Stock.refresh_prices
      @user = current_user
      @tracked_stocks = @user.stocks
      format.js { render partial: 'stocks/list' }
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by(ticker: params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end

    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio!"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.find_by(user: current_user, stock: stock)
    user_stock.destroy
    flash[:notice] = "#{stock.name} was successfully removed from your portfolio!"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.matches(params[:friend])
      @friends = @friends.reject { |friend| friend.id == current_user.id }
      if @friends.present?
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Could not find friend..."
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend email or name to search for"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<% if @friends.present? %>
  <div class="row">
    <div class="col-9">
      <div class="row">
        <% @friends.each do |friend| %>
          <div class="col-sm-4">
            <div class="card mt-4">
              <%= image_tag 'undraw_profile_pic_ic5t.svg', class: "card-img-top p-4" %>
              <div class="card-body">
                <h5 class="card-title"><%= friend.full_name %></h5>
                <p class="card-text">Email: <%= friend.email %></p>
                <%= link_to 'View profile', user_path(friend), class: 'btn btn-success btn-sm' %>
                <%= link_to 'Stop following', friendship_path(friend),
                            method: :delete,
                            class: 'btn btn-warning btn-sm' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice.present? || alert.present? %>
  <% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>

    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'MyPortfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to "My Friends", my_friends_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                <%= fa_icon('edit') %> Edit profile
              <% end %>
              <%= link_to user_path(current_user), class: 'dropdown-item' do %>
                <%= fa_icon('user') %> View Profile
              <% end %>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item user-name">
            <%= fa_icon :user %>
            <%= "#{current_user.full_name}" %>
          </li>
          <li class="nav-item'">
            <%= link_to('Log out', destroy_user_session_path, class: 'btn btn-danger logout-button', method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinanceTracker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/stocks/_list.html.erb
<% if @tracked_stocks.present? %>
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Last price</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>

            <td>
              <% if current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock),
                            method: :delete,
                            data: { confirm: "Are you sure you want to stop tracking #{stock.name}?" },
                            class: 'btn btn-warning btn-sm' %>
              <% else %>
                <% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                              class: 'btn btn-success', method: :post %>
                <% else %>
                <span class="badge badge-secondary">
                  You are already tracking
                  <% if current_user.under_stock_limit? %>
                    <%= stock.ticker %>!
                  <% else %>
                    <%= User::MAX_STOCK_COUNT %> stocks!
                  <% end %>
                </span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% if current_user.id == @user.id %>
      <div class="col-3">
        <%= link_to refresh_stock_prices_path, class: 'btn btn-success',
                    method: :post, remote: :true, id: 'refresh-stock-prices-btn',
                    data: { disable_with: '<i class="fa fa-spinner fa-spin"></i>' } do %>
          Refresh stock prices <%= fa_icon 'refresh' %>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Not tracking any stocks.</p>
<% end %>

app/views/stocks/_list.js.erb
document.querySelector('#stocks-list').innerHTML = '<%= j render 'stocks/list.html' %>';

app/views/users/_friend_result.html.erb
<%= render 'layouts/messages' %>

<% if @friends.present? %>
  <div class="row">
    <div class="col-9">
      <div class="row">
        <% @friends.each do |friend| %>
          <div class="col-sm-4">
            <div class="card bg-light mt-4">
              <%= image_tag 'undraw_profile_pic_ic5t.svg', class: "card-img-top p-4" %>
              <div class="card-body">
                <h5 class="card-title text-success"><%= friend.full_name %></h5>
                <p class="card-text">Email: <%= friend.email %></p>
                <%= link_to 'View profile', user_path(friend), class: 'btn btn-success btn-sm' %>
                <% if current_user.not_friends_with?(friend) %>
                  <%= link_to 'Follow friend?', friendships_path(friend: friend),
                              class: 'btn btn-success btn-sm', method: :post %>
                <% else %>
                  <span class="badge badge-secondary">You are friends</span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'friend_result.html' %>'

app/views/users/_result.html.erb
<%= render 'layouts/messages' %>

<% if @stock.present? %>
  <div class="card card-header results-block">
    <strong>Symbol:</strong><%= @stock.ticker %>
    <strong>Name:</strong><%= @stock.name %>
    <strong>Price:</strong><%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                  class: 'btn btn-success', method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if current_user.under_stock_limit? %>
          <%= @stock.ticker %>!
        <% else %>
          <%= User::MAX_STOCK_COUNT %> stocks!
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/result.html') %>'

app/views/users/my_friends.html.erb
<h1>My portfolio</h1>
<div class="search-area">
  <h3>Search friends</h3>
  <%= form_tag search_friend_path, method: :get, remote: true do %>
    <div class="form-group row">
      <div class="col-sm-9 pr-0">
        <%= text_field_tag :friend, params[:friend], placeholder: 'Name or email',
                           autofocus: true,
                           class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 pl-0">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results"></div>
<%= render 'friends/list' %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area">
  <h3>Search stock</h3>
  <%= form_tag search_stock_path, method: :get, remote: true do %>
    <div class="form-group row">
      <div class="col-sm-9 pr-0">
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol',
                           autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 pl-0">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon "search 2x" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results"></div>
<div id="stocks-list">
  <%= render 'stocks/list' %>
</div>

app/views/users/show.html.erb
<h2>User details:</h2>

<div class="row">
  <div class="col-3">
    <div class="card mb-3 bg-light">
      <%= image_tag 'undraw_profile_pic_ic5t.svg', class: "card-img-top p-4" %>
      <div class="card-body">
        <h5 class="card-title text-success"><%= @user.full_name %></h5>
        <p class="card-text"><%= @user.email %></p>
        <% if current_user.not_friends_with?(@user) %>
          <%= link_to 'Follow friend?', friendships_path(friend: @user),
                      class: 'btn btn-success btn-sm', method: :post %>
        <% else %>
          <span class="badge badge-secondary">You are friends</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'stocks/list' %>

app/views/welcome/index.html.erb
<h2>Welcome to the finance-tracker app!</h2>
<div class="m-4">
  <p>
    This is the Stock Tracker Social Media App implementation from
    <%= link_to 'The Complete Ruby on Rails Developer Course',
                'https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/',
                target: '_blank' %>.
    <br>
    Github section-by-section commits (+ a couple of extras) can be found at
    <%= link_to 'https://github.com/dancristianb/finance-tracker',
                'https://github.com/dancristianb/finance-tracker',
                target: '_blank'%>.
  </p>

  <% if current_user.present? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete,
                class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-info' %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-info' %>
  <% end %>
</div>